CREATE TABLE USERS (userKey UUID PRIMARY KEY, emailAddress TEXT NOT NULL, password TEXT NOT NULL, firstName TEXT NOT NULL, lastName TEXT NOT NULL, emailVerified BOOLEAN DEFAULT FALSE);

CREATE TABLE CONGRESSMESSAGES (id BIGSERIAL, userEmail TEXT NOT NULL, subject TEXT NOT NULL, textBody TEXT NOT NULL);

